name: Local Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Image
        run: docker pull rrajivsingh/backend-app:latest

      - name: Stop and Remove Old Container (if it exists)
        shell: powershell
        run: |
          $container = docker ps -aq -f "name=^backend$"

          if ($container) {
            Write-Host "Existing container found. Stopping..."
            docker stop backend

            Write-Host "Removing old container..."
            docker rm backend
          }
          else {
            Write-Host "No existing container found. Fresh deployment."
          }

      - name: Start New Container
        run: docker run -d --name backend -p 3000:3000 rrajivsingh/backend-app:latest